name: doconce
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - numpy
  - matplotlib
  - pandas
  - regex
  - autopep8
  - isort
  - jupyter
  - jupyter_contrib_nbextensions
  - texlive-core
  - pip:
    - DocOnce
    - jupyter-book
