# This file is generated by make, do not edit

# Building html
doconce format html reference1.do.txt

# Building pdf
doconce format pdflatex reference1.do.txt --latex_code_style=vrb --execute && \
	pdflatex reference1.tex

# Building jupyter notebook
doconce format ipynb reference1.do.txt --execute

# Building markdown
doconce format markdown reference1.do.txt
