# This file is generated by make, do not edit

# Building html
# Target: ../pub/exercise1.html
doconce format html exercise1.do.txt --execute=abort \
	--output=../pub/exercise1.html && \
	cd ../pub && ln -fs ../src/.doconce_figure_cache .

# Building pdf
# Target: ../pub/exercise1.pdf
doconce format pdflatex exercise1.do.txt --latex_code_style=vrb \
	--execute=abort --toc_depth=3 && \
	pdflatex exercise1.tex && \
	mv exercise1.pdf ../pub/exercise1.pdf

# Building jupyter notebook for exercises without answers and solutions
# Target: ../pub/exercise1.ipynb
doconce format ipynb exercise1.do.txt --execute=abort --without_solutions --without_answers \
	\
--output=../pub/exercise1.ipynb

# Building markdown
# Target: ../pub/exercise1.md
doconce format markdown exercise1.do.txt \
	--output=../pub/exercise1.md

# Building jupyter notebook for exercises with answers and solutions
# Target: ../pub/exercise1-solutions.ipynb
doconce format ipynb exercise1.do.txt --execute=abort \
	--output=../pub/exercise1-solutions.ipynb
