# This file is generated by make, do not edit

# Building html
doconce format html include1.do.txt --execute && \
	mv include1.html ../pub/include1.html

# Building pdf
doconce format pdflatex include1.do.txt --latex_code_style=vrb --execute && \
	pdflatex include1.tex && \
	mv include1.pdf ../pub/include1.pdf

# Building jupyter notebook
doconce format ipynb include1.do.txt --execute && \
	mv include1.ipynb ../pub/include1.ipynb

# Building markdown
doconce format markdown include1.do.txt && \
	mv include1.md ../pub/include1.md
