# This file is generated by make, do not edit

# Building html
doconce format html slide1.do.txt --execute && \
	mv slide1.html ../pub/slide1.html

# Building pdf
doconce format pdflatex slide1.do.txt --latex_code_style=vrb --execute && \
	pdflatex slide1.tex && \
	mv slide1.pdf ../pub/slide1.pdf && \
	doconce clean

# Building jupyter notebook
doconce format ipynb slide1.do.txt --execute && \
	mv slide1.ipynb ../pub/slide1.ipynb

# Building markdown
doconce format markdown slide1.do.txt && \
	mv slide1.md ../pub/slide1.md
