name: Manually test with latest doconce
# Manually triggered: test with very latest doconce from source
on: workflow_dispatch
jobs:
  compile_doconce_latest:
    # uses the latest version (commit) of doconce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lexnederbragt/doconce:1.5.13.1_py39
      - run: docker pull lexnederbragt/doconce:1.5.13.1_py39
      - run: docker run -v $(pwd):/app -t lexnederbragt/doconce:1.5.13.1_py39 /bin/bash -c "source activate doconce && git clone --depth 1 https://github.com/doconce/doconce.git && cd doconce && pip install --upgrade . && cd /app && cd src && make cleanall && make"
